name: apeworx-starter-kit
contracts_folder: contracts
deployments:
  ethereum:
    sepolia:


solidity:
  import_remapping:
    - "@openzeppelin=https://github.com/OpenZeppelin/openzeppelin-contracts"

default_ecosystem: ethereum